### ISSUE TITLE
Intellisense for object methods/properties and database objects

### ISSUE THREAD

**Issue by Orionsg** [chriscamicas/vscode-abl#12]
I just discovered this extension for OpenEdge ABL and I to a large degree now use VScode instead of the OpenEdge IDE and editor. Thanks for developing this very useful extension!

I have a couple of issues / questions / enhancement requests -- I am not sure which, because some of it may be due to lack of proper setup.

While the syntax checking works great for the ABL as such, I don't see any suggestions (intellisense) for object method, properties as well as database tables and fields. If e.g. I define an object to a class where the class file resides in the same folder as the procedure I am editing. Does this have to do with propath setup or is this feature just not implemented in the extension?

As for the database objects, it would be nice to have intellisense as well. However, I don't see how editor would be able to get the database object names as there are no settings for connection to the database, so I guess this is not possible?

The code base I am working on at the moment is straight client-server in Windows 7, i.e. no application server involved. I assume that this precludes the running and debugging features or can it, nevertheless, be brought to work?

There is mention of creating a local .openedge.json file for the project, but where is it to placed. So far I have just opened a folder where my ABL source code resides and begun to edit.

**Comment by chriscamicas** [comment]
Hi, thank you for your remarks !

Intellisense is not implemented yet because it requires a lot more work (you'll need a Language Server, and a Grammar that can parse and understand ABL language). 
On the other side, database objects may be more simple to acquire provided you have a DB connection.

Debugging works just fine for every kind of OE application (tty, gui, appserver).
First, you'll have to enable debugging for all OE app: from an elevated cmd prompt
`proDebugEnable -enable-all`
Then, configure a `launch.json` in VSCode with something like this:
```JSON
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Launch myApp",
            "type": "abl",
            "request": "launch",
            "program": "my_startup_file.p",
            "port": 9899,
            "cwd": "${workspaceRoot}",
            "stopOnEntry": true
        }
    ]
}
```
It will start your application with the `debugReady` parameter set to 9899 so the debugger can attach immediately. `stopOnEntry` indicates the debugger will stop the app at the first line, but you can remove this parameter and set your breakpoints whereever you want them.

You may not need to start the process directely from VSCode, provided you have manually started it, ans set `debugReady` (with a specific port). In this case, instead of a `launch` you may use a `attach` request in VSCode:
```JSON
{
    "name": "Attach to debug ready process",
    "type": "abl",
    "request": "attach",
    "address": "localhost",
    "port": 9899,
    "localRoot": "${workspaceRoot}"
}
```
Please note VSCode provides a `Add Configuration` button in the `launch.json` and this extension add 2 templates for ABL 
![abl-launch](https://user-images.githubusercontent.com/7702519/38407935-bae72a1c-397b-11e8-858e-30b37fe7c68a.gif)

The `.openedge.json` file, is quite simple and described in the [extension home page](https://marketplace.visualstudio.com/items?itemName=chriscamicas.openedge-abl)
It is optionnal and only needed if you want to change `proPath` value, or specify a `.pf`. Those 2 will be used to compile, and check the syntax (in a background running process). This file should be located in the root of your workspace.

**Comment by Orionsg** [comment]
Thanks for the detailed clarification!

**Comment by chriscamicas** [comment]
Duplicate with #23
