### ISSUE TITLE
Implement a Language Server for ABL

### ISSUE THREAD

**Issue by chriscamicas** [chriscamicas/vscode-abl#23]
This is needed to add:
- #12 Intellisense for object methods/properties and database objects
- #18 Symbol information (and shortcut `Ctrl+p +@`)
- #20 Code outline

Note: Code Outline uses the SymbolProvider API

References:
- https://code.visualstudio.com/docs/extensions/example-language-server
- https://code.visualstudio.com/docs/extensionAPI/language-support

**Comment by rdnlsmith** [comment]
Hi! I'd like to try and help with this feature, but I'm not sure what you may have already done / what the next step would be. Is there anything in particular I could do that would be useful?

**Comment by chriscamicas** [comment]
Thanks @rdnlsmith for your help.
The idea is to leverage the ABL language syntax and grammar in a language server. There are 2 links in the OP that describes what a language server is.
It will enable feature like: code completion, hover, formatting, definition.
For all this, we need to be able to parse ABL files and 'understand the code'.
Usually we use a Language Recognition (Lexer + Parser), like ANTLR.
The issue #34 is specific to ANTLR, since there is an existing implemention for ABL in Java.
But we could probably start smaller, and move the existing DocumentSymbolProvider in a langage server. It uses regex to identity symbol in the document.

**Comment by RobinHerbots** [comment]
@chriscamicas , @rdnlsmith , 

I think it's best to reuse the current ANTLR implementation from Riverside-software, or to use it as a starting point.  

I added some links for reference ...  
- https://tomassetti.me/antlr-mega-tutorial/
- https://tomassetti.me/language-server-dot-visual-studio/
- https://github.com/Riverside-Software/sonar-openedge/tree/develop/proparse
- https://github.com/antlr/antlr4
- https://github.com/kaby76/AntlrVSIX

**Comment by rdnlsmith** [comment]
It's been a while since I've gotten back to it, but I [did get started](https://github.com/rdnlsmith/vscode-abl/tree/feature/lang-server) on converting this extension to the language server model. As I recall, it's functional at the moment, but it needs some cleanup and it doesn't actually add any new features yet&mdash;just the architecture.

I think it absolutely does make sense to leverage the ANTLR grammar for parsing, but I believe that's *on top of* the LSP conversion and not *instead of* it. Also, I wasn't sure how far along the ANLTR4 version of the ABL parser was, which I believe is necessary for JavaScript/TypeScript support. (I also know basically nothing about ANTLR yet. Thanks for the links!)

**Comment by jmls** [comment]
@chriscamicas , @rdnlsmith : would be interested in helping out - long time abl  (v3) and typescript guy . Use vscode all the time, just not for ABL atm ...

**Comment by rdnlsmith** [comment]
@jmls I have tomorrow off, so I will revisit the work I did last year (I really let this slide! 😕) and get it cleaned up and open a PR so you have something to start from. It took me a while to figure out how to reorganize the code to fit the server/client architecture—no sense making you do that over again!

**Comment by rdnlsmith** [comment]
Okay, so: I revisited my old work-in-progress, but unfortunately it has grown quite stale. I had not realized yesterday that between November and today, this project has incorporated some substantial (and exciting!) improvements via PR #51. 

This PR included massive changes to some of the files I had been working with&mdash;namely, `ablCompletionProvider.ts`, `ablDefinitionProvider.ts`, and it completely replaced `ablParser.ts` with three other, more sophisticated classes. I'm afraid I just don't have the bandwidth to review all of those changes and understand how they would need to be adapted in order to put them server-side instead of client-side, especially as I'm still very new to TypeScript/node. At this point, you will probably have an easier time starting fresh.

I've opened rdnlsmith/vscode-abl#1 in my fork to provide a convenient diff of what I had done vs. the `master` branch as it existed back then. My hope is that this can give @jmls or anyone else a bit of a head-start in implementing the language server off the current `master`.

Here's a bit of a rundown:

- The `src` dir needs to be split into `client/src` and `server/src`. Most of the code that will be staying on the client side can be moved with barely any changes.
- `main.ts` will end up client-side. The server gets its own main file, which in my case was called `server.ts`.
- The client and server each need their own `package.json`, etc., in addition to the `package.json` for the project as a whole.
- The `vscode` imports on the server side need to be replaced with `vscode-languageserver`, which is comparatively limited. This is the main reason I didn't feel confident about adapting the new `ablCompletionProvider.ts` and friends.
- My changes to the project-level `package.json` allow `npm install` and `npm run compile` to work how you would expect for the new "project with two sub-projects" architecture. It took me longer than I'd like to admit to understand what I had to do to get the project building again, but like I said node isn't exactly my comfort zone.
- I got the impression while working on this that the VS Code-specific, client-only approach is better documented than the more agnostic client-server approach. It might be prudent to impose the initial re-organization with only one or two aspects handled server-side, and move other functions from the client to the server more gradually over time. But again, it's very possible that my limited familiarity with node was making it harder for me than it would be for someone else.

Anyways, I hope some of this is helpful!

**Comment by gquerret** [comment]
The language server implementation is available in this VSCode plugin: https://github.com/vscode-abl/vscode-abl
It was decided to create a new project, as the configuration is very different from this project's configuration.
