### ISSUE TITLE
Could vscode-abl reuse proparse antlr4 grammar

### ISSUE THREAD

**Issue by cverbiest** [chriscamicas/vscode-abl#34]
Hi,
this is just an idea, I have little or no experience with javascript and antlr.
I wondered if vscode-abl could benefit from the already existing proparse parser.

Following pages give me the idea it could be possible.

https://github.com/antlr/antlr4/blob/master/doc/javascript-target.md 
https://github.com/Riverside-Software/sonar-openedge/tree/develop/proparse/src/main/antlr4/org/prorefactor/proparse/antlr4

Again I have no experience in the matter. I just think it would be great if only one parser needed to be maintained.

**Comment by chriscamicas** [comment]
Thanks for the suggestion.
It's related to #23 

I already took a look at that grammar (and the previous version in antlr2).
My problem is: it's written in Java and can't work out of the box in JavaScript (nor TypeScript).

We have 2 choices here:
1. embed this grammar as a Java dependency, and create a LanguageServer in Java around it. You could take a look at the [vscode-java extension](https://github.com/redhat-developer/vscode-java). Under the hood, it uses [The Eclipse JDT Language Server](https://github.com/eclipse/eclipse.jdt.ls)
2. modify the existing antlr4 grammar, which is a WIP by @gquerret to be able to use it in JavaScript.

Both approaches involve a lot of work. The first one would probably be the quickest.
But I'm not a Java expert, and feel more comfortable with JavaScript/TypeScript, so I started exploring the second one.
Any help would be greatly appreciated here.

**Comment by gquerret** [comment]
ANTLR4 can generate JavaScript and TS targets, however the lexer is not using ANTLR due to the preprocessor and include files management. So using the new proparse in JS or TS would mean rewriting the lexer code (which is not really difficult, it's simple OO code, and it's not that big), and then use the JS or TS target of the grammar. That's not something I can work on due to the lack of time, but I can help if you need any information.

**Comment by chriscamicas** [comment]
Thanks @gquerret for the reply, we are now full of hope.
Could you explain a bit more why the preprocessor and include files is not compatible with the lexer part of ANTLR ? Does ANTLR4 have better chances to support it (rather than ANTLR2 where the grammar was born intially) ?
I'll give it a try with TS

**Comment by gquerret** [comment]
The same lexer code is used in the legacy ANTLR2 and the new ANTLR4 grammars, it has been written for ANTLR4 and there's a bridge for the token conversion to ANTLR2. Preprocessor, macro expansion, and include files (with named/unnamed parameters) made it impossible to use the builtin lexer in ANTLR4, so that was extracted to standalone classes.

**Comment by gquerret** [comment]
> Could vscode-abl reuse proparse antlr4 grammar

Sure ! That will come soon !
ℹ️ I don't have a precise definition of soon.
